16 wrap multi chart graphics
semiotic-ai/autoagora-agents pull request #17
Opened 2022-12-05 12:30 UTC by tumaysem

Wrapped repeated charts layout, chart and plot creation into relevant functions.
updates #16

2022-12-05 21:07 UTC, aasseman requested changes
Tested and works. Can we however re-enable Anti-Aliasing?
LGTM otherwise.

2022-12-06 17:57 UTC, tumaysem commented on simulation/multi_agent_simulation.py
> +        antialias=True,
Antialiasing enabled here

2022-12-06 19:56 UTC, aasseman commented on simulation/multi_agent_simulation.py
> +        antialias=True,
Ah indeed. Tried with `False` and it indeed looks worse. Somehow the AA on my computer looked worse than I remembered :stuck_out_tongue: .

2022-12-06 19:57 UTC, aasseman approved these changes
LGTM!

I recommend a Squash Merge here.

2022-12-07 03:23 UTC, merged