Random number generation should be consistent based on the simulation configuration
semiotic-ai/autoagora-agents pull request #23
Opened 2022-12-19 12:34 UTC by tumaysem

Random number generation should be consistent based on the simulation configuration.

All noise generation is based on randomness in simulation environment which can generate different output without a seed. value.

fixes #22

2022-12-19 12:40 UTC, tumaysem commented
I really wish to add the parameter to environment node in the config jSON file. But it seems there is a design decision to use the name of the node names as type of the environment to initialize. So I moved the random seed configuration to up one level.

``` js 
"environment": {
  "NoisySharedSubgraph": {
      "noise": true
  }
},
"random_seed":42
```

2022-12-19 18:19 UTC, tkornuta-semiotic commented on simulation/controller.py
> +        np.random.seed(seed_value)
please set in here also seed for pytorch - so the agent's params will be initialized also from that seed

2022-12-19 18:21 UTC, tkornuta-semiotic commented on simulation/controller.py
> +        np.random.seed(seed_value)
https://vandurajan91.medium.com/random-seeds-and-reproducible-results-in-pytorch-211620301eba

2022-12-20 16:20 UTC, tumaysem commented on simulation/controller.py
> +        np.random.seed(seed_value)
https://github.com/semiotic-ai/autoagora-agents/pull/23/commits/ee1bef85685ca2fba4b65dae3df67a548fdaa484

2022-12-26 18:21 UTC, aasseman requested changes
Great! Could you write a simple Unit Test that would confirm that experiments are reproducible?

2022-12-28 08:16 UTC, tumaysem commented
I couldnt't find any agent using 'pytorch' randomization.

2022-12-28 19:20 UTC, aasseman approved these changes
LGTM!

2023-01-02 09:36 UTC, merged