Setup github pages with auto API documentation
semiotic-ai/autoagora-agents pull request #33
Opened 2023-01-29 19:30 UTC by tumaysem

fixes #30

2023-01-30 18:06 UTC, tkornuta-semiotic commented on docs/api.md
> +    AgentFactory:::build --> Agent:::build
alright! we have inheritance diagrams now :)

2023-01-31 02:05 UTC, aasseman requested changes
Looks great!
Would like a few things adjusted (code comments).
Also, there is a couple of small things still needed:
- Link/badge to the docs in `README.md`. Will probably point to something like https://semiotic-ai.github.io/autoagora-agents.
- Version switcher in the docs (or is it something for a future PR?)

2023-01-31 02:05 UTC, aasseman commented on pyproject.toml
> +mkdocstrings-python = "^0.8.3"
Shouldn't that be a dev dependency?

2023-01-31 02:05 UTC, aasseman commented on docs/index.md
> +More details on arguments can be accessed in help (`--h`).
Can't we [DRY](https://en.wikipedia.org//wiki/Don't_repeat_yourself) this? Looks like a copy of `README.md`.

2023-01-31 02:05 UTC, aasseman commented on .github/workflows/gh-pages.yml
> +      - run: mkdocs gh-deploy --force
Multiple suggestions in one (though you may cherry-pick if my assumptions are wrong):
- Freezing the python version to the highest compatible version as indicated by `pyproject.toml` (3.10)
- Using `actions/setup-python`'s integrated cache functionality, in `poetry` mode. (it also works in `pip` mode). Although maybe there was also some other stuff you wanted to cache?
- Using Poetry to load the versions of the mkdocs packages from `poetry.lock`. (I know it's gonna install more packages than necessary, but I wouldn't do that kind of premature optimization. Though it may also make sense to put all the mkdocs stuff in its own [poetry dependency group](https://python-poetry.org/docs/master/managing-dependencies/#dependency-groups)?)
- Missing newline at the end of the file. From the [POSIX standards](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206).
```suggestion
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10
          cache: poetry
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
      - run: poetry install --only=dev
      - run: poetry run mkdocs gh-deploy --force

```

2023-01-31 18:40 UTC, tumaysem commented on pyproject.toml
> +mkdocstrings-python = "^0.8.3"
updated in https://github.com/semiotic-ai/autoagora-agents/pull/33/commits/1120b299905caffb472833778b11a18b76368798

2023-02-02 13:06 UTC, tumaysem commented on docs/index.md
> +More details on arguments can be accessed in help (`--h`).
https://github.com/semiotic-ai/autoagora-agents/pull/33/commits/0e4e1c49a28a56b41c294d449753a41762136b60

2023-02-02 13:08 UTC, tumaysem commented on .github/workflows/gh-pages.yml
> +      - run: mkdocs gh-deploy --force
fully updated the workflow with semantic versioning support
https://github.com/semiotic-ai/autoagora-agents/pull/33/commits/0e4e1c49a28a56b41c294d449753a41762136b60

2023-02-02 20:06 UTC, aasseman requested changes
I tested in a fork, and now the directory structure of the `gh-pages` branch is:
```
.
├── latest
│   ├── 404.html
│   ├── api
│   ├── index.html
│   └── sim
├── v1.2.1
│   ├── 404.html
│   ├── api
│   ├── assets
│   ├── index.html
│   ├── objects.inv
│   ├── search
│   ├── sim
│   ├── sitemap.xml
│   └── sitemap.xml.gz
└── versions.json
```
The problem is that GH pages supports only a single index in `/` or `/docs/`, so now it can't serve anything anymore. Also, there's no switch between versions in the UI.

2023-02-02 20:06 UTC, aasseman commented on .github/workflows/gh-pages.yml
> +        run: echo "latest=v$(poetry run semantic-release print-version --current)" >> $GITHUB_OUTPUT
This will not work most of the time, because it will only print the latest version based on the tags, and at this point in the CI, the tag may not exist yet.
Here's how I tested the scenario where there's a new semantic version, but no new tag yet:
```
$ poetry run semantic-release print-version --current
1.2.1
$ git commit --allow-empty -m "fix: test"
$ poetry run semantic-release print-version --current
1.2.1
```

I still think that it would be more robust to make this a job that's right after the semantic release like I did here: https://github.com/semiotic-ai/autoagora/blob/4a156c9e35d5a27a5850d8e2f6c31bb579165b1d/.github/workflows/semver.yml#L32

The problem I had however, is that `python-semantic-release` does not output anything to GH's CI. I made a dirty patch [here](https://github.com/aasseman/python-semantic-release/commit/fbf59380616fc66d418e058e5f40c88532b75269) to make the above work, but it turns out that [GH is phasing out that method of setting outputs...](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) I suppose you could use my special version of `python-semantic-versioning` for now, and we'll have to find a solution to the GH change after.

https://github.com/semantic-release/semantic-release does set outputs.

2023-02-06 15:43 UTC, tumaysem commented on .github/workflows/gh-pages.yml
> +        run: echo "latest=v$(poetry run semantic-release print-version --current)" >> $GITHUB_OUTPUT
Just select the gh-pages branch and /
the mike set-default method will generate a redirect index.html

2023-02-06 16:57 UTC, tumaysem commented on .github/workflows/gh-pages.yml
> +        run: echo "latest=v$(poetry run semantic-release print-version --current)" >> $GITHUB_OUTPUT
There is a  problem with your build 
https://github.com/semiotic-ai/autoagora/actions/runs/4057060063/jobs/6982341996
I was stuck at the same point.

2023-02-07 21:47 UTC, tumaysem commented on .github/workflows/gh-pages.yml
> +        run: echo "latest=v$(poetry run semantic-release print-version --current)" >> $GITHUB_OUTPUT
And I've returned from the wonderland. I added github ouput feature to [semantic-release ](https://github.com/python-semantic-release/python-semantic-release/compare/master...tumaysem:python-semantic-release:master)

And versioning is working as expected.

2023-02-07 23:16 UTC, aasseman requested changes
Tested on a fork, and it all works! :green_circle: 
Only a couple of things left:
- Link/badge to the docs in README.md. Will probably point to something like https://semiotic-ai.github.io/autoagora-agents.
- Rabase onto master

2023-02-08 17:52 UTC, aasseman requested changes
Sorry, one more tiny thing :grin:

2023-02-08 17:52 UTC, aasseman commented on README.md
> +[![Documents](https://img.shields.io/github/actions/workflow/status/semiotic-ai/autoagora-agents/gh_pages.yml?label=docs)](https://semoitic-ai.github.io/autoagora-agents/)
It's called either `Docs` or `Documentation`.

2023-02-08 19:47 UTC, aasseman approved these changes
It all works :tada: 

One thing I'd like improved next is to have `python-semantic-release` run only once, instead of both in `.github/workflows/gh-pages.yml` and `.github/workflows/semver.yml`.

2023-02-08 19:47 UTC, merged